export const TYPE_TEXT = 'TYPE_TEXT'
export const TYPE_TOGGLE = 'TYPE_TOGGLE'
export const TYPE_PICKLIST = 'TYPE_PICKLIST'
export const TYPE_SLIDER = 'TYPE_SLIDER'

export const panelSetup = {}

export const PANEL_MAIN = 'PANEL_MAIN'
export const SLIDER_ANIMATION_RATE = 'SLIDER_ANIMATION_RATE'
export const SLIDER_MAX_ITERATIONS = 'SLIDER_MAX_ITERATIONS'
panelSetup[PANEL_MAIN] = [
  'Main Controls',
  SLIDER_ANIMATION_RATE,
  SLIDER_MAX_ITERATIONS,
]

export const PANEL_ITERATION_0 = 'PANEL_ITERATION_0'
export const SLIDER_SCALE_START = 'SLIDER_SCALE_START'
export const SLIDER_ANGLE_START = 'SLIDER_ANGLE_START'
panelSetup[PANEL_ITERATION_0] = [
  'Start',
  SLIDER_SCALE_START,
  SLIDER_ANGLE_START,
]

export const PANEL_F1_C1 = 'PANEL_F1_C1'
export const SLIDER_SCALE_1_1 = 'SLIDER_SCALE_1_1'
export const SLIDER_ANGLE_1_1 = 'SLIDER_ANGLE_1_1'
panelSetup[PANEL_F1_C1] = [
  'Child 1',
  SLIDER_SCALE_1_1,
  SLIDER_ANGLE_1_1,
]

export const PANEL_F1_C2 = 'PANEL_F1_C2'
export const SLIDER_SCALE_1_2 = 'SLIDER_SCALE_1_2'
export const SLIDER_ANGLE_1_2 = 'SLIDER_ANGLE_1_2'
panelSetup[PANEL_F1_C2] = [
  'Child 2',
  SLIDER_SCALE_1_2,
  SLIDER_ANGLE_1_2,
]
