export const TYPE_TEXT = 'TYPE_TEXT'
export const TYPE_TOGGLE = 'TYPE_TOGGLE'
export const TYPE_PICKLIST = 'TYPE_PICKLIST'
export const TYPE_SLIDER = 'TYPE_SLIDER'

export const panelSetup = {}

export const PANEL_GENERAL = 'PANEL_GENERAL'
export const TOGGLE_DISPLAY_STATEVIEW = 'TOGGLE_DISPLAY_STATEVIEW'
panelSetup[PANEL_GENERAL] = [
  'General',
  TOGGLE_DISPLAY_STATEVIEW,
]

export const PANEL_ITERATION = 'PANEL_ITERATION'
export const SLIDER_MAX_ITERATIONS = 'SLIDER_MAX_ITERATIONS'
export const SLIDER_MIN_PX = 'SLIDER_MIN_PX'
export const SLIDER_MAX_COUNT = 'SLIDER_MAX_COUNT'
export const SLIDER_MAX_CALC_TIME_US = 'SLIDER_MAX_CALC_TIME_US'
export const SLIDER_MAX_DRAW_TIME_US = 'SLIDER_MAX_DRAW_TIME_US'
panelSetup[PANEL_ITERATION] = [
  'Iteration',
  SLIDER_MAX_ITERATIONS,
  SLIDER_MIN_PX,
  SLIDER_MAX_COUNT,
  SLIDER_MAX_CALC_TIME_US,
  SLIDER_MAX_DRAW_TIME_US,
]

export const PANEL_HULL = 'PANEL_HULL'
export const SLIDER_HULL_ITERATIONS = 'SLIDER_HULL_ITERATIONS'
export const SLIDER_HULL_ROUNDING = 'SLIDER_HULL_ROUNDING'
export const SLIDER_HULL_MAX_CALC_TIME_US = 'SLIDER_HULL_MAX_CALC_TIME_US'
panelSetup[PANEL_HULL] = [
  'Convex Hull',
  SLIDER_HULL_ITERATIONS,
  SLIDER_HULL_ROUNDING,
  SLIDER_HULL_MAX_CALC_TIME_US,
]

export const PANEL_CANVAS = 'PANEL_CANVAS'
export const TOGGLE_ANIMATE = 'TOGGLE_ANIMATE'
export const SLIDER_ANIMATION_RATE = 'SLIDER_ANIMATION_RATE'
export const SLIDER_CANVAS_Y = 'SLIDER_CANVAS_Y'
export const TOGGLE_DISPLAY_STATS = 'TOGGLE_DISPLAY_STATS'
panelSetup[PANEL_CANVAS] = [
  'Canvas',
  TOGGLE_ANIMATE,
  SLIDER_ANIMATION_RATE,
  SLIDER_CANVAS_Y,
  TOGGLE_DISPLAY_STATS,
]

export const PANEL_START = 'PANEL_START'
export const SLIDER_START_X = 'SLIDER_START_X'
export const SLIDER_START_Y = 'SLIDER_START_Y'
export const SLIDER_SCALE_START = 'SLIDER_SCALE_START'
export const SLIDER_ANGLE_START = 'SLIDER_ANGLE_START'
export const SLIDER_RATIO_B2_B1 = 'SLIDER_RATIO_B2_B1'
export const TOGGLE_REFLECT_START = 'TOGGLE_REFLECT_START'
panelSetup[PANEL_START] = [
  'Start',
  SLIDER_START_X,
  SLIDER_START_Y,
  SLIDER_SCALE_START,
  SLIDER_ANGLE_START,
  TOGGLE_REFLECT_START,
  SLIDER_RATIO_B2_B1,
]

export const PANEL_F1_C1 = 'PANEL_F1_C1'
export const SLIDER_ID_1_1 = 'SLIDER_ID_1_1'
export const SLIDER_SCALE_1_1 = 'SLIDER_SCALE_1_1'
export const SLIDER_ANGLE_1_1 = 'SLIDER_ANGLE_1_1'
export const TOGGLE_REFLECT_1_1 = 'TOGGLE_REFLECT_1_1'
panelSetup[PANEL_F1_C1] = [
  'Branch 1, Child 1',
  SLIDER_ID_1_1,
  SLIDER_SCALE_1_1,
  SLIDER_ANGLE_1_1,
  TOGGLE_REFLECT_1_1,
]

export const PANEL_F1_C2 = 'PANEL_F1_C2'
export const SLIDER_ID_1_2 = 'SLIDER_ID_1_2'
export const SLIDER_SCALE_1_2 = 'SLIDER_SCALE_1_2'
export const SLIDER_ANGLE_1_2 = 'SLIDER_ANGLE_1_2'
export const TOGGLE_REFLECT_1_2 = 'TOGGLE_REFLECT_1_2'
panelSetup[PANEL_F1_C2] = [
  'Branch 1, Child 2',
  SLIDER_ID_1_2,
  SLIDER_SCALE_1_2,
  SLIDER_ANGLE_1_2,
  TOGGLE_REFLECT_1_2,
]

export const PANEL_F2_C1 = 'PANEL_F2_C1'
export const SLIDER_ID_2_1 = 'SLIDER_ID_2_1'
export const SLIDER_SCALE_2_1 = 'SLIDER_SCALE_2_1'
export const SLIDER_ANGLE_2_1 = 'SLIDER_ANGLE_2_1'
export const TOGGLE_REFLECT_2_1 = 'TOGGLE_REFLECT_2_1'
panelSetup[PANEL_F2_C1] = [
  'Branch 2, Child 1',
  SLIDER_ID_2_1,
  SLIDER_SCALE_2_1,
  SLIDER_ANGLE_2_1,
  TOGGLE_REFLECT_2_1,
]

export const PANEL_F2_C2 = 'PANEL_F2_C2'
export const SLIDER_ID_2_2 = 'SLIDER_ID_2_2'
export const SLIDER_SCALE_2_2 = 'SLIDER_SCALE_2_2'
export const SLIDER_ANGLE_2_2 = 'SLIDER_ANGLE_2_2'
export const TOGGLE_REFLECT_2_2 = 'TOGGLE_REFLECT_2_2'
panelSetup[PANEL_F2_C2] = [
  'Branch 2, Child 2',
  SLIDER_ID_2_2,
  SLIDER_SCALE_2_2,
  SLIDER_ANGLE_2_2,
  TOGGLE_REFLECT_2_2,
]
